# Generated by Django 4.2.6 on 2023-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_svg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouth_svg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AvatarComponent',
        ),
    ]
